### ISSUE TITLE
Which research paper does this repository corresponds to? 

### ISSUE THREAD

**Issue by Miles762** [aitor-alvarez/gnn-speech-emotion#1]
Is the repository based on the research paper "Representation Learning with Graph Neural Networks for
Speech Emotion Recognition" ?

**Comment by aitor-alvarez** [comment]
I never published this work since the results did not contain much novelty. I just made it open so others can use it as a baseline if they want to or choose to do so.

**Comment by Miles762** [comment]
Okay thanks for your response.
